/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosNewRouteImport } from './routes/todos/new'
import { Route as TodosTodoIdRouteImport } from './routes/todos/$todoId'
import { Route as AccountEditRouteImport } from './routes/account/edit'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodosRoute,
} as any)
const TodosNewRoute = TodosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TodosRoute,
} as any)
const TodosTodoIdRoute = TodosTodoIdRouteImport.update({
  id: '/$todoId',
  path: '/$todoId',
  getParentRoute: () => TodosRoute,
} as any)
const AccountEditRoute = AccountEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/todos': typeof TodosRouteWithChildren
  '/account/edit': typeof AccountEditRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/': typeof TodosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/account/edit': typeof AccountEditRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
  '/todos/new': typeof TodosNewRoute
  '/todos': typeof TodosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/todos': typeof TodosRouteWithChildren
  '/account/edit': typeof AccountEditRoute
  '/todos/$todoId': typeof TodosTodoIdRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/': typeof TodosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/todos'
    | '/account/edit'
    | '/todos/$todoId'
    | '/todos/new'
    | '/todos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/account/edit'
    | '/todos/$todoId'
    | '/todos/new'
    | '/todos'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/todos'
    | '/account/edit'
    | '/todos/$todoId'
    | '/todos/new'
    | '/todos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  TodosRoute: typeof TodosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/'
      fullPath: '/todos/'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof TodosRoute
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewRouteImport
      parentRoute: typeof TodosRoute
    }
    '/todos/$todoId': {
      id: '/todos/$todoId'
      path: '/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdRouteImport
      parentRoute: typeof TodosRoute
    }
    '/account/edit': {
      id: '/account/edit'
      path: '/edit'
      fullPath: '/account/edit'
      preLoaderRoute: typeof AccountEditRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountEditRoute: typeof AccountEditRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountEditRoute: AccountEditRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface TodosRouteChildren {
  TodosTodoIdRoute: typeof TodosTodoIdRoute
  TodosNewRoute: typeof TodosNewRoute
  TodosIndexRoute: typeof TodosIndexRoute
}

const TodosRouteChildren: TodosRouteChildren = {
  TodosTodoIdRoute: TodosTodoIdRoute,
  TodosNewRoute: TodosNewRoute,
  TodosIndexRoute: TodosIndexRoute,
}

const TodosRouteWithChildren = TodosRoute._addFileChildren(TodosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  TodosRoute: TodosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
